version: '3.8'

services:
  catalog:
    build:
      context: .
      dockerfile: catalog-module/Dockerfile
    ports:
      - "4575:4575"
    networks:
      - microservicesNetwork

  order:
    build:
      context: .
      dockerfile: order-module/Dockerfile
    ports:
      - "3300:3300"
    depends_on:
      - catalog
    networks:
      - microservicesNetwork

  gateway:
    build:
      context: .
      dockerfile: gateway-module/Dockerfile
    ports:
      - "4567:4567"
    depends_on:
      - catalog
      - order
    networks:
      - microservicesNetwork

networks:
  microservicesNetwork:
    driver: bridge