version: "3.9"

services:
  catalog:
    image: catalog:1.0
    build:
      context: .
      dockerfile: catalog-module/Dockerfile
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
    environment:
      - PORT=4575
    networks:
      - microservicesNetwork

  order:
    image: order:1.0
    build:
      context: .
      dockerfile: order-module/Dockerfile
    ports:
      - "3300:3300"
    depends_on:
      - catalog
    networks:
      - microservicesNetwork

  gateway:
    image: gateway:1.0
    build:
      context: .
      dockerfile: gateway-module/Dockerfile
    ports:
      - "4567:4567"
    depends_on:
      - catalog
      - order
    networks:
      - microservicesNetwork

networks:
  microservicesNetwork:
    driver: bridge
